In [5]:
import numpy as np

# Create a single-dimensional array
arr1 = np.array([1, 2, 3, 4, 5])
print(arr1)   # [1 2 3 4 5]

# Create a multi-dimensional array
arr2 = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(arr2)
# [[1 2 3]
#  [4 5 6]
#  [7 8 9]]

# Perform arithmetic operations on two multi-dimensional arrays
arr3 = np.array([[1, 2], [3, 4]])
arr4 = np.array([[5, 6], [7, 8]])
print(arr3 + arr4)
print(arr3 - arr4)

print(arr3 * arr4)

print(arr3 / arr4)



#accessing elements
print(arr3[0][1]+arr4[1][0])
#accessing elements
print(arr3[0][1]*arr4[1][0])


[1 2 3 4 5]
[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]
[[ 5 12]
 [21 32]]
[[0.2        0.33333333]
 [0.42857143 0.5       ]]
9
14
