In [1]:
import numpy as np

a = np.array([1, 2, 3])
a = a + 1
print(a)

[2 3 4]


In [3]:
c = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
d = np.array([1, 0, -1])
result = c - d[:, np.newaxis]
result2=c-d
print(result)
print(result2)

[[ 0  1  2]
 [ 4  5  6]
 [ 8  9 10]]
[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [5]:
f = np.array([[1, 2, 3], [4, 5, 6]])
#add a new row to f that consists of the sum of each column of f
sum_row = np.sum(f, axis=0)
result = np.vstack([f, sum_row])
print(result)

[[1 2 3]
 [4 5 6]
 [5 7 9]]
