In [1]:
import numpy as np

# Create a scalar tensor
scalar_tensor = np.array(5)
print("Scalar Tensor:\n", scalar_tensor)

# Create a vector tensor
vector_tensor = np.array([1, 2, 3])
print("\nVector Tensor:\n", vector_tensor)

# Create a matrix tensor
matrix_tensor = np.array([[1, 2], [3, 4]])
print("\nMatrix Tensor:\n", matrix_tensor)

# Create a 3D tensor
tensor_3d = np.array([[[1, 2], [3, 4]], [[5, 6], [7, 8]]])
print("\n3D Tensor:\n", tensor_3d)
print(tensor_3d.shape)

# Create a random tensor (as a NumPy array)
random_tensor = np.random.normal(size=(3, 3))
print("\nRandom Tensor:\n", random_tensor)

Scalar Tensor:
 5

Vector Tensor:
 [1 2 3]

Matrix Tensor:
 [[1 2]
 [3 4]]

3D Tensor:
 [[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]
(2, 2, 2)

Random Tensor:
 [[-0.73145043 -0.07422228  0.34452886]
 [-1.13989412 -1.8887973  -0.37774678]
 [-0.80868092  0.85315331 -0.08089854]]


In [2]:
import numpy as np

# Create a 3D tensor
tensor_3d = np.array([[[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]],
                      [[13, 14, 15, 16], [17, 18, 19, 20], [21, 22, 23, 24]]])

# Reshape the tensor to a 2D tensor
tensor_2d = tensor_3d.reshape((2, 12))

# Print the shapes of the tensors
print("Original Tensor Shape:", tensor_3d.shape)
print("Reshaped Tensor Shape:", tensor_2d.shape)

Original Tensor Shape: (2, 3, 4)
Reshaped Tensor Shape: (2, 12)


In [3]:
import numpy as np

a = np.array([[1, 2], [3, 4]])
b = np.array([[5, 6], [7, 8]])

result = np.dot(a, b)

print(result)

[[19 22]
 [43 50]]
